### ISSUE TITLE
Error: Provisioning failed.

### ISSUE THREAD

**Issue by marlonlamancio** [kovshenin/sail#1]
Hello, I managed to install Sail on my Macbook correctly, when provisioning an instance in DO the following error occurred:

```
sail init --size=s-1vcpu-1gb-intel --region=sfo3 --provider-token=MY_TOKEN --email=MY_DO_EMAIL

# Initializing
- Init successful, application id: 0a837ebb0f3b33b9
- Writing SSH keys to .sail/ssh.key
- Writing .sail/config.json

# Provisioning servers
- Provision scheduled successfully, waiting...
- Uploading SSH key to DigitalOcean
- Creating a new Droplet
- Waiting for Droplet to boot
- Droplet up and running, creating DNS records

Error: Provisioning failed. Please try again later.
```

Then I tried to add a domain to the instance but the following error occurred:

```
sail domain add MYDOMAIN.COM
Error: API error: Not ready. Current status: installing
```

I don't know what to do from now on. Could you give me a direction? Thanks

**Comment by kovshenin** [comment]
Hey @marlonlamancio! Looking at the API logs, it seems like you attempted to create this project a couple of days ago? If so, could you please try again?

It seems like there was a small change in the DigitalOcean API where they'd change the state of the droplet prior to assigning it an IP address. I've added another waiter to make sure we obtain an IP address prior to continuing in the API code over the weekend, so it should all be working fine now.

If it still doesn't work with a fresh init, please let me know the application id and I'll look into it.

**Comment by marlonlamancio** [comment]
Excellent! Now it worked fine! Thanks for the quick response and for this great tool. I'm going to run some more tests and I'm already spreading the word. Cheers!

**Comment by kovshenin** [comment]
Thanks so much @marlonlamancio, glad to hear you're enjoying it! Let me know if you run into any other problems.

**Comment by kovshenin** [comment]
@marlonlamancio you might also want to look into your DigitalOcean control panel, that failed provision probably left a running server behind, which you wouldn't want to be billed for, so just destroy it using the control panel.

**Comment by marlonlamancio** [comment]
Yes, I've already destroyed this droplet. Thanks
