### ISSUE TITLE
Support SSL for Mapped Subdomains

### ISSUE THREAD

**Issue by BrookeDot** [kovshenin/sail#15]
I've set up my first site with Sail and have been enjoying it. However, I ran into a snag when it came to adding SSL. I ran the following commands:

```
sail domain add sub.example.com
sail domain make-primary sub.example.com
```
It was `sail domain make-https sub.example.com` which failed:

```
sail domain make-https sub.example.com
Let's Encrypt ToS: https://community.letsencrypt.org/tos
Do you agree to the Let's Encrypt ToS? [y/N]: y
# Requesting and installing SSL for domains
- Scheduled make-https for sub.example.com
- Waiting for make-https to complete
- Generating Nginx configs for example.com
- Requesting certificate from Certbot for group example.com
Error: Task state failure
```

As some additional context, the DNS record for `sub.example.com` was added in DigitalOcean but the root (example.com) is pointing to another droplet. Looks like what is happening is that sail is trying to first setup the domain as `example.com` So In `etc/nginx/config.d` I have an `example.com` folder where I'd expect to see `sub.example.com`. That may be a different bug and is less urgent but wanted to note it. 

I was able to get SSL working by manually modifying the server.

```
sail ssh --root
certbot -n certonly -m user@example.com --agree-tos --standalone --http-01-port 8088 --expand -d sub.example.com
vi /etc/nginx/config.d/example.com
```
And I added the following:

```
listen 443 ssl; # managed by Certbot

    # RSA certificate
    ssl_certificate /etc/letsencrypt/live/sub.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/sub.example.com/privkey.pem; # managed by Certbot

    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot

    # Redirect non-https traffic to https
    if ($scheme != "https") {
        return 301 https://$host$request_uri;
    } # managed by Certbot

```

Then `nginx restart` and was good to go.

I guess this is either a feature or a bug report depending on how you look at it for sail to support subdomains including SSH support. 

Thanks!

**Comment by kovshenin** [comment]
Hi @BrookeDot, good to see you here, thanks for giving Sail a spin!! :)

There is indeed a limit on subdomains in Sail prior to version 0.10.0 (currently in main), so whenever you added a subdomain it would ask you to add the domain first, which then causes problems with Certbot if the parent domain is not pointing to the server. In the newer version, where domain management is fully client-side, you can add subdomains without their parents, and Certbot will also treat them right.

If you'd like to give the newer version a spin, you'll have to [build it from source](https://sailed.io/kb/install/), or you can wait for a PyPI/Homebrew release later this week.

Also note that 0.10.x will not be compatible with 0.9.x environments. I'll write up a short migration guide with the release.

**Comment by kovshenin** [comment]
Release notes here: https://github.com/kovshenin/sail/releases/tag/0.10.0

**Comment by BrookeDot** [comment]
I just tested with 0.10.0 and the subdomain setup is working as expected. Thanks for the quick response. In my case since it was a staging site I just `sail destroyed` the existing droplet and recreated it with the new version but good to know a migration path is possible. 

Thanks again, I'll mark this as closed.

**Comment by kovshenin** [comment]
No problem, thanks so much for testing! If you bump into any other problems, don't hesitate to get in touch!
