### ISSUE TITLE
Remove DNS records upon destroy

### ISSUE THREAD

**Issue by BrookeDot** [kovshenin/sail#16]
One of the features that makes sail awesome is the ability to manage the DNS for sites which point to DigitalOcean. However, when a site is destroyed with `sail destroy` the DNS records are not removed. This could lead to the domain being used in nonferrous ways or just cause confusion later.

My recommendation would be to remove these records by default. Alternatively, you could prompt if the user wants the DNS removed, but think in most cases since the droplet IP will change it should just happen behind the scenes. Middle ground would be a parameter `sail destroy -- keep-dns` which would satisfy advanced use case while still being user friendly.

**Comment by kovshenin** [comment]
Thanks for the request @BrookeDot, this should be implemented in main now and shipped soon.

The default behavior, as you suggested, is to delete DNS records for any domains added to the Sail project, and if no more records are left, it'll even delete the zone itself. For more advanced cases, users can use `--skip-dns`, the same flag supported by some `sail domain` commands.

Let me know if you have any additional feedback and thanks again!
