### ISSUE TITLE
Add .gitignore/.deployignore support for partial deploys?

### ISSUE THREAD

**Issue by acerus** [kovshenin/sail#17]
Sometimes it's really necessary to exclude some folders from deploy. Example: local copy is used for development and there are all kinds of developer-only stuff there, like node_modules. Would be great to have an option where I can specify what folders/files to exclude from deploy at all times.

**Comment by kovshenin** [comment]
FWIW partial (or sparse) deploys are already implemented in Sail, you just need to give it a path, like this:

```
sail deploy wp-content/plugins # this will deploy the plugins directory only
```

But if node_modules is inside your plugin directory, then that doesn't really help. It's also annoying to have to type it out all the time, its purpose is to use it in rare edge cases. So yes, .deployignore (and .gitignore) support is a great idea, will look into doing a first pass in the next release.

**Comment by kovshenin** [comment]
Docs: https://sailed.io/kb/deployignore/
