### ISSUE TITLE
Simplify Local db updates

### ISSUE THREAD

**Issue by acerus** [kovshenin/sail#21]
Having worked with Sail for awhile I really wish this can be done with a single command:

![image](https://user-images.githubusercontent.com/13415518/144680161-2c7674d0-210e-4b83-9554-c8e58d766433.png)

**Comment by kovshenin** [comment]
There's a `--json` flag in the `sail db export` routine in 0.10.2, which returns the absolute path to the export file. This should help make a short bash script for your scenario. Let me know if that doesn't help!
