### ISSUE TITLE
[feat] WordPress settings on app init by yml config

### ISSUE THREAD

**Issue by DimaMinka** [kovshenin/sail#4]
Hello
I talking about WordPress Blueprint Settings for default options by some *.yml file.
[Some example from my pet project.](https://github.com/wpi-pw/app/blob/master/wpi-config/05-settings.yml)

**Comment by soulseekah** [comment]
Димас, брат, братишка, напиши на русском, нихера не понятно что ты хочешь...

**Comment by DimaMinka** [comment]
Так ты вроде уже добавил эту секцию в PR.

**Comment by soulseekah** [comment]
Drupal uses settings.
WordPress uses options.

https://github.com/kovshenin/sail/commit/6ad9d14a2f922a92bc385fc997cde872d34c75ec

**Comment by kovshenin** [comment]
Fixed in #3
