### ISSUE TITLE
Doc typo

### ISSUE THREAD

**Issue by Bowriverstudio** [kovshenin/sail#47]
Hello and thanks for the project,

On Page: https://sailed.io/kb/init/

```bash
sail init --provider_token=YOUR_TOKEN --email=ADMIN_EMAIL
```

Should be

```bash
sail init --provider_token=YOUR-TOKEN --email=ADMIN_EMAIL
```

**Comment by kovshenin** [comment]
Hah, took me a while to figure it out. I guess you meant the `--provider_token` argument should be `--provider-token` :) Thanks for the report, will fix.

**Comment by Bowriverstudio** [comment]
lol you are right.  Thanks again for the product.

**Comment by kovshenin** [comment]
Thanks for the kind words! This has been fixed in the private docs repo, closing.
