### ISSUE TITLE
[fix] blueprint plugin activation error  

### ISSUE THREAD

**Issue by DimaMinka** [kovshenin/sail#8]
### Description
when I changed the yaml file, add some new plugins and run the command:
```bash
sail blueprint bp.yaml
```
I got the error:
```bash
# Applying blueprint: bp.yaml
- Installing plugins
- wporg/tweaks-for-elementor=latest
- wporg/classic-editor=latest
- Activating plugins
- Error: Error: Please specify one or more plugins, or use --all.
```
on first run after `sail init` all worked perfect, the sample.yaml installed woo and seo without any issues. Its happened only when I try to run blueprint again on exist project.

p.s. new themes installed and activated without any issues. 

### Steps to reproduce
1. sail init
2. sail blueprint bp.yaml (based on sample.yaml)
3. add or change one of the plugins in bp.yaml
4. sail blueprint bp.yaml  - again

### Version 
Sail 0.9.13

**Comment by kovshenin** [comment]
Thanks for reporting this! This was fixed in the API server and deployed to production.

Let me know if you run into any other trouble!
