### ISSUE TITLE
How do you change the IP address of the droplet?

### ISSUE THREAD

**Issue by g000m** [kovshenin/sail#80]
I moved a sail droplet, resulting in a new IP address. I was hoping that there'd be a dynamic DNS update for the *.justsailed.io cname. I changed the CNAME to A records w/ the host IP to get the sites back up, but the sail cli no longer reaches the host.

What's the correct way to associate sailed w/ the new IP?

**Comment by kovshenin** [comment]
Hi @g000m, unfortunately you can't change the existing subdomain IP address, it's assigned only once and is permanent until released. To continue using Sail in your case you could edit the .sail/config.json file and hard-code the IP address instead of the internal subdomain.

Hope that helps!

**Comment by g000m** [comment]
Ok, had to change hostname and ip in config.json to be able to ssh again.

Is droplet_id used for anything? Any reason to update it?

**Comment by kovshenin** [comment]
Yeah, the droplet_id is used if you're destroying the server, or if you're changing the primary domain for your site.
